version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root5113
      POSTGRES_DB: devops_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - app-network          # <--- Add this line

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: root5113
      DB_HOST: db
      DB_NAME: devops_db
      OPENWEATHER_API_KEY: a48728497ad6498ced5b7d0eca124b60
      PORT: 5000
    ports:
      - "5003:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network: